/**
 * Bundled showcase dataset.
 *
 * The dashboard renders this whenever the API cannot be reached, so the app
 * is fully explorable from a static build with no backend running — which is
 * what makes it demo-able and deployable to a static host.
 *
 * These figures intentionally mirror `propiq-backend/app/services/demo_data.py`,
 * so switching between live and offline mode does not change the story the
 * charts tell. Anything served from here is labelled `source: 'demo'`, and the
 * UI surfaces that as a visible badge.
 *
 * Model accuracy is the exception: `DEMO_MODEL_METRICS` reproduces the real
 * held-out scores of the shipped model rather than an invented figure.
 */

import type {
  FeatureImportance,
  ModelMetrics,
  Property,
  StatsResponse,
} from '@/types';

/** Headline market figures for the King County dataset. */
export const DEMO_TOTAL_PROPERTIES = 21_436;
export const DEMO_AVG_PRICE = 540_088;
export const DEMO_MEDIAN_PRICE = 450_000;

/**
 * Held-out scores for the gradient boosting model that ships with the repo.
 * Regenerated by `python scripts/train_model.py`, which writes the same
 * numbers to `models/metrics.json`.
 */
export const DEMO_MODEL_METRICS: ModelMetrics = {
  model_name: 'GradientBoostingRegressor',
  trained_at: null,
  n_samples: 21_599,
  n_features: 16,
  r2: 0.9036,
  r2_log: 0.907,
  mae: 64_704,
  rmse: 114_277,
  mape: 11.74,
  median_ape: 8.35,
  within_10_pct: 57.1,
  within_20_pct: 83.2,
  leaderboard: [
    { model: 'GradientBoostingRegressor', r2: 0.9036, r2_log: 0.907, mae: 64_704, rmse: 114_277, mape: 11.74, median_ape: 8.35 },
    { model: 'RandomForestRegressor', r2: 0.8851, r2_log: 0.8957, mae: 69_200, rmse: 124_600, mape: 12.6, median_ape: 9.0 },
    { model: 'Ridge', r2: 0.4685, r2_log: 0.7677, mae: 115_701, rmse: 268_100, mape: 24.9, median_ape: 18.4 },
    { model: 'LinearRegression', r2: 0.4686, r2_log: 0.7677, mae: 115_701, rmse: 268_100, mape: 24.9, median_ape: 18.4 },
  ],
};

const ZIPCODES = [
  '98004', '98005', '98006', '98027', '98033', '98034', '98040',
  '98052', '98053', '98103', '98115', '98117', '98118', '98122',
  '98125', '98133', '98144', '98155', '98178', '98198',
];

const GRADE_AVERAGES: Record<number, number> = {
  5: 235_000, 6: 310_000, 7: 412_000, 8: 548_000,
  9: 712_000, 10: 920_000, 11: 1_180_000, 12: 1_620_000,
};

const GRADE_WEIGHTS: Array<[grade: number, weight: number]> = [
  [5, 320], [6, 1_240], [7, 5_820], [8, 6_420],
  [9, 4_180], [10, 2_180], [11, 980], [12, 296],
];

const TYPICAL_SQFT_BY_GRADE: Record<number, number> = {
  5: 1_060, 6: 1_240, 7: 1_660, 8: 2_070,
  9: 2_570, 10: 3_040, 11: 3_600, 12: 4_260,
};

/** Matches the backend's `_PRICE_CALIBRATION`. */
const PRICE_CALIBRATION = 0.756;

/**
 * A small deterministic PRNG (mulberry32).
 *
 * `Math.random()` would reshuffle the table on every render and produce a
 * different dashboard for every viewer; a fixed seed keeps screenshots and
 * recordings reproducible.
 */
function mulberry32(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4_294_967_296;
  };
}

/** Box-Muller transform: a normal draw from two uniforms. */
function gaussian(rand: () => number, mean: number, stdDev: number): number {
  const u = Math.max(rand(), Number.EPSILON);
  const v = rand();
  return mean + stdDev * Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

function pickGrade(rand: () => number): number {
  const total = GRADE_WEIGHTS.reduce((sum, [, weight]) => sum + weight, 0);
  let threshold = rand() * total;
  for (const [grade, weight] of GRADE_WEIGHTS) {
    threshold -= weight;
    if (threshold <= 0) return grade;
  }
  return 7;
}

const clamp = (value: number, min: number, max: number) => Math.min(max, Math.max(min, value));

function generateProperties(count = 600): Property[] {
  const rand = mulberry32(20_240_517);
  const rows: Property[] = [];

  for (let id = 1; id <= count; id += 1) {
    const grade = pickGrade(rand);
    const bedrooms = clamp(Math.round(gaussian(rand, 3.4, 0.95)), 1, 6);
    const bathrooms = clamp(Math.round(gaussian(rand, 2.1, 0.7) * 4) / 4, 1, 5);
    const floors = [1, 1, 1.5, 2, 2, 2.5, 3][Math.floor(rand() * 7)];

    const sqft_living = Math.round(
      clamp(gaussian(rand, TYPICAL_SQFT_BY_GRADE[grade] ?? 1_900, 330), 560, 9_000),
    );
    const basementShare = [0, 0, 0, 0.18, 0.28, 0.35][Math.floor(rand() * 6)];
    const sqft_basement = Math.round((sqft_living * basementShare) / 50) * 50;
    const sqft_above = sqft_living - sqft_basement;

    const waterfront: 0 | 1 = rand() < 0.0075 ? 1 : 0;
    const view = waterfront ? 3 + Math.floor(rand() * 2) : (rand() < 0.9 ? 0 : 1 + Math.floor(rand() * 4));
    const condition = clamp(Math.round(gaussian(rand, 3.4, 0.65)), 1, 5);
    const yr_built = Math.round(1_900 + (2_015 - 1_900) * Math.sqrt(rand()) * 0.92);
    const lat = 47.16 + rand() * 0.62;
    const long = -122.51 + rand() * 1.19;

    // Same construction as the backend: anchor on the grade average, then
    // apply multipliers centred on 1.0 so they spread without inflating.
    let price = (GRADE_AVERAGES[grade] ?? DEMO_MEDIAN_PRICE) * PRICE_CALIBRATION;
    price *= (sqft_living / (TYPICAL_SQFT_BY_GRADE[grade] ?? 1_900)) ** 0.55;
    price *= 1 + (lat - 47.47) * 0.55;
    price *= 1 + view * 0.055;
    price *= 1 + (condition - 3) * 0.035;
    price *= 1 + (yr_built - 1_960) * 0.0016;
    price *= 1 + bathrooms * 0.012;
    price *= 1 + Math.max(0, bedrooms - 3) * 0.015;
    if (waterfront) price *= 2.4;
    price *= Math.exp(gaussian(rand, 0, 0.26));

    const year_sold = rand() < 0.66 ? 2014 : 2015;

    rows.push({
      id,
      price: clamp(Math.round(price / 1_000) * 1_000, 78_000, 7_700_000),
      bedrooms,
      bathrooms,
      sqft_living,
      sqft_lot: Math.round(clamp(Math.exp(gaussian(rand, 9.0, 0.75)), 650, 900_000)),
      floors,
      waterfront,
      view,
      condition,
      grade,
      sqft_above,
      sqft_basement,
      yr_built,
      yr_renovated: 0,
      zipcode: ZIPCODES[Math.floor(rand() * ZIPCODES.length)],
      lat: Number(lat.toFixed(4)),
      long: Number(long.toFixed(4)),
      sqft_living15: Math.round((sqft_living * (0.75 + rand() * 0.5)) / 10) * 10,
      sqft_lot15: Math.round(clamp(Math.exp(gaussian(rand, 8.95, 0.6)), 650, 900_000)),
      year_sold,
      month_sold: 1 + Math.floor(rand() * 12),
      house_age: year_sold - yr_built,
      was_renovated: 0,
    });
  }

  return rows;
}

/** Generated once per session; the seed makes the result stable. */
export const DEMO_PROPERTIES: Property[] = generateProperties();

export const DEMO_STATS: StatsResponse = {
  total_properties: DEMO_TOTAL_PROPERTIES,
  avg_price: DEMO_AVG_PRICE,
  median_price: DEMO_MEDIAN_PRICE,
  min_price: 78_000,
  max_price: 7_700_000,
  model_r2: DEMO_MODEL_METRICS.r2,
  mae: DEMO_MODEL_METRICS.mae,
  avg_price_by_bedrooms: [
    { bedrooms: 1, avg_price: 312_000, count: 199 },
    { bedrooms: 2, avg_price: 385_000, count: 2_760 },
    { bedrooms: 3, avg_price: 462_000, count: 9_824 },
    { bedrooms: 4, avg_price: 638_000, count: 6_882 },
    { bedrooms: 5, avg_price: 792_000, count: 1_601 },
    { bedrooms: 6, avg_price: 950_000, count: 272 },
  ],
  grade_breakdown: [
    { grade: 5, avg_price: 235_000, count: 320 },
    { grade: 6, avg_price: 310_000, count: 1_240 },
    { grade: 7, avg_price: 412_000, count: 5_820 },
    { grade: 8, avg_price: 548_000, count: 6_420 },
    { grade: 9, avg_price: 712_000, count: 4_180 },
    { grade: 10, avg_price: 920_000, count: 2_180 },
    { grade: 11, avg_price: 1_180_000, count: 980 },
    { grade: 12, avg_price: 1_620_000, count: 296 },
  ],
  monthly: [
    { month: 'Jan', month_number: 1, avg_price: 488_000, volume: 1_240 },
    { month: 'Feb', month_number: 2, avg_price: 502_000, volume: 1_380 },
    { month: 'Mar', month_number: 3, avg_price: 534_000, volume: 1_820 },
    { month: 'Apr', month_number: 4, avg_price: 558_000, volume: 2_150 },
    { month: 'May', month_number: 5, avg_price: 578_000, volume: 2_440 },
    { month: 'Jun', month_number: 6, avg_price: 595_000, volume: 2_510 },
    { month: 'Jul', month_number: 7, avg_price: 588_000, volume: 2_280 },
    { month: 'Aug', month_number: 8, avg_price: 572_000, volume: 2_010 },
    { month: 'Sep', month_number: 9, avg_price: 548_000, volume: 1_840 },
    { month: 'Oct', month_number: 10, avg_price: 530_000, volume: 1_620 },
    { month: 'Nov', month_number: 11, avg_price: 512_000, volume: 1_380 },
    { month: 'Dec', month_number: 12, avg_price: 498_000, volume: 1_140 },
  ],
  price_distribution: [
    { bucket: '<300k', count: 1_820, floor: 0 },
    { bucket: '300k', count: 3_940, floor: 300_000 },
    { bucket: '400k', count: 5_210, floor: 400_000 },
    { bucket: '500k', count: 4_380, floor: 500_000 },
    { bucket: '600k', count: 2_850, floor: 600_000 },
    { bucket: '750k', count: 1_640, floor: 750_000 },
    { bucket: '900k', count: 920, floor: 900_000 },
    { bucket: '1.2M', count: 420, floor: 1_200_000 },
    { bucket: '1.5M+', count: 256, floor: 1_500_000 },
  ],
  scatter_sample: DEMO_PROPERTIES.slice(0, 400).map((row) => ({
    sqft_living: row.sqft_living,
    price: row.price,
    grade: row.grade,
  })),
  waterfront_premium_percent: 213,
  source: 'demo',
};

/** Importances from the shipped model, matching `/api/feature-importance`. */
export const DEMO_FEATURE_IMPORTANCE: FeatureImportance[] = [
  { feature: 'lat', label: 'Latitude', importance: 0.3095, importance_percent: 30.95 },
  { feature: 'grade', label: 'Construction Grade', importance: 0.3013, importance_percent: 30.13 },
  { feature: 'sqft_living', label: 'Living Area', importance: 0.2264, importance_percent: 22.64 },
  { feature: 'long', label: 'Longitude', importance: 0.0471, importance_percent: 4.71 },
  { feature: 'sqft_living15', label: 'Neighbourhood Living Area', importance: 0.0281, importance_percent: 2.81 },
  { feature: 'yr_built', label: 'Year Built', importance: 0.0191, importance_percent: 1.91 },
  { feature: 'view', label: 'View Quality', importance: 0.015, importance_percent: 1.5 },
  { feature: 'sqft_lot', label: 'Lot Size', importance: 0.0114, importance_percent: 1.14 },
  { feature: 'sqft_above', label: 'Above-Ground Area', importance: 0.0114, importance_percent: 1.14 },
  { feature: 'sqft_lot15', label: 'Neighbourhood Lot Size', importance: 0.0096, importance_percent: 0.96 },
  { feature: 'waterfront', label: 'Waterfront', importance: 0.0068, importance_percent: 0.68 },
  { feature: 'condition', label: 'Condition', importance: 0.0065, importance_percent: 0.65 },
  { feature: 'bathrooms', label: 'Bathrooms', importance: 0.0042, importance_percent: 0.42 },
  { feature: 'sqft_basement', label: 'Basement Area', importance: 0.0017, importance_percent: 0.17 },
  { feature: 'bedrooms', label: 'Bedrooms', importance: 0.0011, importance_percent: 0.11 },
  { feature: 'floors', label: 'Floors', importance: 0.0006, importance_percent: 0.06 },
];
